name: Sync to Hugging Face hub

on:
  push:
    branches: [master]  # Run on every push to the main branch

  workflow_dispatch:  # Allows you to trigger the workflow manually from the Actions tab

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
          lfs: true       # Ensure that Git LFS files are fetched

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://agshiv92:$HF_TOKEN@huggingface.co/spaces/agshiv92/test2 main --force
