name: Push to Hugging Face

on:
  push:
    branches: [master]  # Trigger the workflow on push to the 'master' branch
  pull_request:
    branches: [master]  # Trigger the workflow on pull requests to the 'main' branch
  workflow_dispatch:  # Allows manual trigger of the workflow from the Actions tab

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
          lfs: true  # Enable Git LFS support

      - name: Check large files
        uses: ActionsDesk/lfs-warning@v2.0
        with:
          filesizelimit: 10485760  # 10MB size limit check

      - name: Install Git LFS (Large File Storage)
        run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs
          git lfs install

      - name: Set up Git Config
        run: |
          git config --global user.email "agshiv92@gmail.com"  # Use your GitHub email
          git config --global user.name "agshiv92"  # Use your GitHub name

      - name: Pull from Hugging Face (main)
        run: |
          git remote add space https://agshiv92:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/agshiv92/TorontoCanadaChapter_CanPolicyInsight
          git pull space main  # Pull from 'main' branch

      - name: Push to Hugging Face (master)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}  # Hugging Face token stored in GitHub secrets
        run: |
          git push --force space master  # Push to 'master' branch

      - name: Push complete
        run: echo "Pushed successfully to Hugging Face"
