on:
  push:
    branches:
      - master  # Trigger the workflow on push to the 'master' branch

jobs:
  push-to-huggingface:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Git LFS (Large File Storage)
      run: |
        sudo apt-get update
        sudo apt-get install -y git-lfs
        git lfs install
    - name: Set up Git Config and Hugging Face Repository
      run: |
        git config --global user.email "agshiv92@gmail.com"  # Use your GitHub email
        git config --global user.name "agshiv92"  # Use your GitHub name
        git remote add hf https://huggingface.co/spaces/agshiv92/TorontoCanadaChapter_CanPolicyInsight  # Hugging Face repo URL
        git fetch hf  # Fetch the latest changes from Hugging Face
    - name: Handle merge conflicts and pull the latest from Hugging Face
      run: |
        # Try rebasing first, if that fails, fallback to a merge
        git pull hf main --rebase || (git rebase --abort && git pull hf main --no-rebase)  # Rebase first, if it fails do a normal merge
    - name: Resolve merge conflicts
      run: |
        git add .  # Add all resolved files
        git commit -m "Resolve merge conflicts" || echo "No conflicts to resolve"
    - name: Track files with Git LFS (if necessary)
      run: |
        # Track specific file types with Git LFS if needed
        git lfs track "*.your_file_extension"  # Replace with specific file types like "*.png", "*.zip", etc.
        git add .gitattributes || echo "No changes to track"
        git commit -m "Track large files with Git LFS" || echo "No changes to commit"
    - name: Push to Hugging Face
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}  # Use the Hugging Face token from GitHub secrets
      run: |
        git push hf master --force-with-lease  # Force push to Hugging Face with safety to avoid overwriting any recent commits
    - name: Push complete
      run: echo "Pushed successfully to Hugging Face"
